import { WS_CAPABILITIES, type ClientType } from '@openaidy/shared-types';

export const CAPABILITY_PRESETS: Record<ClientType, string[]> = {
  web: [
    WS_CAPABILITIES.SESSIONS_READ,
    WS_CAPABILITIES.SESSIONS_WRITE,
    WS_CAPABILITIES.SESSIONS_STREAM,
    WS_CAPABILITIES.SESSIONS_DELETE,
    WS_CAPABILITIES.AGENTS_READ,
    WS_CAPABILITIES.AGENTS_INVOKE,
    WS_CAPABILITIES.PROVIDERS_READ,
    WS_CAPABILITIES.CONFIG_READ,
    WS_CAPABILITIES.SYSTEM_NOTIFY,
  ],
  cli: [
    WS_CAPABILITIES.SESSIONS_READ,
    WS_CAPABILITIES.SESSIONS_WRITE,
    WS_CAPABILITIES.SESSIONS_STREAM,
    WS_CAPABILITIES.SESSIONS_DELETE,
    WS_CAPABILITIES.AGENTS_READ,
    WS_CAPABILITIES.AGENTS_INVOKE,
    WS_CAPABILITIES.PROVIDERS_READ,
    WS_CAPABILITIES.PROVIDERS_INVOKE,
    WS_CAPABILITIES.CONFIG_READ,
    WS_CAPABILITIES.CONFIG_WRITE,
    WS_CAPABILITIES.NODE_INVOKE,
    WS_CAPABILITIES.NODE_DESCRIBE,
    WS_CAPABILITIES.PAIRING_APPROVE,
    WS_CAPABILITIES.PAIRING_DENY,
    WS_CAPABILITIES.SYSTEM_RUN,
    WS_CAPABILITIES.SYSTEM_NOTIFY,
  ],
  mobile: [
    WS_CAPABILITIES.SESSIONS_READ,
    WS_CAPABILITIES.SESSIONS_WRITE,
    WS_CAPABILITIES.SESSIONS_STREAM,
    WS_CAPABILITIES.AGENTS_READ,
    WS_CAPABILITIES.AGENTS_INVOKE,
    WS_CAPABILITIES.PROVIDERS_READ,
    WS_CAPABILITIES.CONFIG_READ,
    WS_CAPABILITIES.NODE_INVOKE,
    WS_CAPABILITIES.SYSTEM_NOTIFY,
  ],
  channel: [
    WS_CAPABILITIES.SESSIONS_READ,
    WS_CAPABILITIES.SESSIONS_WRITE,
    WS_CAPABILITIES.SESSIONS_STREAM,
    WS_CAPABILITIES.AGENTS_READ,
    WS_CAPABILITIES.AGENTS_INVOKE,
    WS_CAPABILITIES.PROVIDERS_READ,
    WS_CAPABILITIES.PROVIDERS_INVOKE,
    WS_CAPABILITIES.SYSTEM_NOTIFY,
  ],
};

export function getCapabilityPreset(clientType: ClientType): string[] {
  return CAPABILITY_PRESETS[clientType];
}
