/**
 * Create Command - Initialize a new addon project
 */

import fs from 'node:fs';
import path from 'node:path';
import {
  validateAddonName,
  validateAddonId,
  validateTemplateName,
} from '../../utils/validation.js';
import { slugify, resolveAddonsDir } from '../../utils/project.js';
import { installAddon } from './install.js';
import { buildAddon } from './build.js';

export interface CreateOptions {
  directory?: string;
  template?: string;
  noGit?: boolean;
  noInstall?: boolean;
  serverUrl?: string;
  token?: string;
}

export interface CreateResult {
  success: boolean;
  message: string;
  projectPath?: string;
}

/**
 * Create a new addon project
 */
export async function createAddon(
  name: string,
  options: CreateOptions = {},
): Promise<CreateResult> {
  const {
    directory = resolveAddonsDir(),
    template = 'basic',
    noGit = false,
    noInstall: _noInstall = false,
  } = options;

  // Validate addon name
  if (!validateAddonName(name)) {
    return {
      success: false,
      message:
        'Invalid addon name. Use letters, numbers, spaces, and hyphens only.',
    };
  }

  const addonId = slugify(name);

  // Validate addon ID
  if (!validateAddonId(addonId)) {
    return {
      success: false,
      message: 'Generated addon ID is invalid. Please choose a different name.',
    };
  }

  // Validate template
  if (!validateTemplateName(template)) {
    return {
      success: false,
      message: `Invalid template: ${template}. Valid templates are: basic, agent, multi-page, config`,
    };
  }

  const projectPath = path.join(directory, addonId);

  // Check if directory already exists
  if (fs.existsSync(projectPath)) {
    return {
      success: false,
      message: `Directory already exists: ${projectPath}`,
    };
  }

  try {
    // Create project directory
    fs.mkdirSync(projectPath, { recursive: true });

    // Create basic addon structure
    await createBasicStructure(projectPath, addonId, name, template);

    // Initialize git if requested
    if (!noGit) {
      await initGit(projectPath);
    }

    // Auto-build so the UI is immediately available (non-fatal on failure)
    await buildAddon(projectPath);

    // Auto-register with the running server so it appears in the UI immediately.
    // Failure here is non-fatal — the files are already created.
    await installAddon(projectPath, {
      serverUrl: options.serverUrl,
      token: options.token,
      requireBuild: false,
    });

    return {
      success: true,
      message: `Successfully created addon: ${name}`,
      projectPath,
    };
  } catch (error) {
    return {
      success: false,
      message: `Failed to create addon: ${error instanceof Error ? error.message : 'Unknown error'}`,
    };
  }
}

/**
 * Create basic addon file structure
 */
async function createBasicStructure(
  projectPath: string,
  addonId: string,
  name: string,
  _template: string,
): Promise<void> {
  // Create addon.json manifest
  const manifest = {
    id: addonId,
    name,
    version: '1.0.0',
    description: `${name} addon for OpenAidy`,
    openaidy: {
      minVersion: '0.0.0',
    },
    entry: 'dist/index.js',
    permissions: [],
    ui: {
      sidebar: {
        icon: 'box',
        label: name,
        order: 100,
      },
      routes: [
        {
          path: `/${addonId}`,
          component: 'MainPage',
        },
      ],
    },
    agents: [],
    config: {
      schema: {
        type: 'object',
        properties: {},
      },
      defaults: {},
    },
    dependencies: {},
  };

  fs.writeFileSync(
    path.join(projectPath, 'addon.json'),
    JSON.stringify(manifest, null, 2),
  );

  // Create package.json
  const packageJson = {
    name: `@openaidy/addon-${addonId}`,
    version: '1.0.0',
    description: `${name} addon for OpenAidy`,
    main: 'dist/index.js',
    scripts: {
      build: 'openaidy build',
      dev: 'openaidy dev',
      test: 'openaidy test',
      validate: 'openaidy validate',
    },
    dependencies: {
      '@openaidy/sdk': 'workspace:*',
    },
    devDependencies: {
      typescript: '^5.0.0',
    },
  };

  fs.writeFileSync(
    path.join(projectPath, 'package.json'),
    JSON.stringify(packageJson, null, 2),
  );

  // Create src directory with main entry
  fs.mkdirSync(path.join(projectPath, 'src'), { recursive: true });

  const mainContent = `/**
 * ${name} Addon
 * Generated by OpenAidy CLI
 *
 * Edit src/index.html to build your addon's UI.
 */

export const id = '${addonId}';
export const version = '1.0.0';
`;

  fs.writeFileSync(path.join(projectPath, 'src', 'index.ts'), mainContent);

  // Create the main UI page
  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name}</title>
  <script src="http://localhost:3001/sdk/openaidy-sdk.js"></script>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #0f172a;
      color: #e2e8f0;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }
    header {
      padding: 20px 24px 12px;
      border-bottom: 1px solid #1e293b;
    }
    header h1 { font-size: 1.25rem; font-weight: 600; color: #f1f5f9; }
    header p { font-size: 0.813rem; color: #64748b; margin-top: 2px; }
    main { flex: 1; padding: 24px; }
    .card {
      background: #1e293b;
      border: 1px solid #334155;
      border-radius: 12px;
      padding: 20px;
      margin-bottom: 16px;
    }
    .card h2 { font-size: 1rem; font-weight: 600; margin-bottom: 8px; color: #f1f5f9; }
    .card p { font-size: 0.875rem; color: #94a3b8; line-height: 1.6; }
    .badge {
      display: inline-block;
      padding: 2px 10px;
      border-radius: 20px;
      font-size: 0.75rem;
      font-weight: 500;
      background: #0ea5e9;
      color: #fff;
      margin-top: 10px;
    }
  </style>
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>OpenAidy Addon &middot; v1.0.0</p>
  </header>
  <main>
    <div class="card">
      <h2>Welcome to ${name}</h2>
      <p>This is your addon's main page. Edit <code>src/index.html</code> to build your UI, then run <code>pnpm openaidy addon build</code> to apply changes.</p>
      <span class="badge" id="status">Connecting...</span>
    </div>
    <div class="card" id="data-card" style="display:none">
      <h2>Sessions</h2>
      <p id="sessions-output">Loading...</p>
    </div>
  </main>
  <script>
    OpenAidy.ready(async function(sdk) {
      document.getElementById('status').textContent = 'Connected';
      try {
        const result = await sdk.listSessions();
        const count = result.sessions ? result.sessions.length : 0;
        document.getElementById('sessions-output').textContent = count + ' active session(s)';
        document.getElementById('data-card').style.display = 'block';
      } catch (e) {
        document.getElementById('sessions-output').textContent = 'Error: ' + e.message;
        document.getElementById('data-card').style.display = 'block';
      }
    });
  </script>
</body>
</html>
`;

  fs.writeFileSync(path.join(projectPath, 'src', 'index.html'), indexHtml);

  // Create config-schema.json
  const configSchema = {
    type: 'object',
    properties: {},
  };

  fs.writeFileSync(
    path.join(projectPath, 'config-schema.json'),
    JSON.stringify(configSchema, null, 2),
  );

  // Create tsconfig.json
  const tsconfig = {
    compilerOptions: {
      target: 'ES2020',
      module: 'ESNext',
      moduleResolution: 'bundler',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      outDir: 'dist',
      rootDir: 'src',
    },
    include: ['src/**/*'],
  };

  fs.writeFileSync(
    path.join(projectPath, 'tsconfig.json'),
    JSON.stringify(tsconfig, null, 2),
  );

  // Create README.md
  const readme = `# ${name}

${manifest.description}

## Installation

\`\`\`bash
npm install
\`\`\`

## Development

\`\`\`bash
npm run dev
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`

## Validate

\`\`\`bash
npm run validate
\`\`\`
`;

  fs.writeFileSync(path.join(projectPath, 'README.md'), readme);
}

/**
 * Initialize git repository
 */
async function initGit(projectPath: string): Promise<void> {
  try {
    const { execSync } = await import('node:child_process');
    execSync('git init', { cwd: projectPath, stdio: 'ignore' });
  } catch {
    // Git initialization failed, ignore
  }
}
